/**
 * Created by Administrator on 14-9-11.
 */
Ext.define("NotesApp.controller.Notes",{
    extend:"Ext.app.Controller",
    lanuch:function(){
        this.callParent();
        console.log("launch");
    },
    init:function(){
        this.callParent();
        console.log("init");
    },
    config:{
        refs:{
            newNoteBtn:"#new-note-btn"
        },
        control:{
            newNoteBtn:{
                tap:"onNewNote"
            }
        }
    },
    onNewNote:function(){
        console.log("onNewNote");
    }
})