/**
 * Created by Administrator on 14-9-14.
 */
Ext.define("NotesApp.view.NoteEditor", {
    extend:"Ext.Container",
    alias:"widget.noteeditor",
    config:{
        items:[
            {
                xtype:"toolbar",
                dock:"top",
                title:"Edit Note",
                items:[
                    {
                        xtype:"button",
                        text:"Home",
                        ui:"back",
                        handler:function(){
                        }
                    },{
                        xtype:"spacer"
                    },{
                        xtype:"button",
                        text:"Save",
                        ui:"action",
                        handler:function(){
                        }
                    }
                ]
            },
            {
                xtype:"toolbar",
                dock:"bottom",
                items:[
                    {xtype:"spacer"},
                    {
                        xtype:"button",
                        iconCls:"trash",
                        iconMask:true,
                        handler:function(){
                        }
                    }
                ]
            },
            {
                xtype:"panel",
                items:[
                    {
                        xtype:"textfield",
                        name:"title",
                        label:"Title",
                        required:true
                    },
                    {
                        xtype:"textareafield",
                        name:"narrative",
                        label:"Narrative"
                    }
                ]
            }
        ]
    }
})